spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: file:./app/
cds:
  security:
    mock:
      users:
        privi:
          privileged: true
          password: privi
        admin:
          "roles[0]": admin
          password: admin
          attributes:
            "businessPartner[0]": "10401010"
        user:
          password: user
    authentication:
      normalize-provider-tenant: true
  data-source:
    auto-config:
      enabled: false
  query.hierarchy.enabled: true
---
spring:
  config.activate.on-profile: cloud
cds:
  query.hierarchy.enabled: true
logging:
  level:
    com.sap.cds.persistence.sql: DEBUG
    com.sap.cds.util.transformations: DEBUG  
